package flux.lastbus.com.easysobuy.database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;
import flux.lastbus.com.easysobuy.database.module.SearchDB;
import flux.lastbus.com.easysobuy.database.module.SearchNetKeyDB;
import flux.lastbus.com.easysobuy.database.module.UserInfoDB;
import flux.lastbus.com.easysobuy.database.module.UsersDB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchDBDaoConfig;
    private final DaoConfig usersDBDaoConfig;
    private final DaoConfig userInfoDBDaoConfig;
    private final DaoConfig searchNetKeyDBDaoConfig;

    private final SearchDBDao searchDBDao;
    private final UsersDBDao usersDBDao;
    private final UserInfoDBDao userInfoDBDao;
    private final SearchNetKeyDBDao searchNetKeyDBDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchDBDaoConfig = daoConfigMap.get(SearchDBDao.class).clone();
        searchDBDaoConfig.initIdentityScope(type);

        usersDBDaoConfig = daoConfigMap.get(UsersDBDao.class).clone();
        usersDBDaoConfig.initIdentityScope(type);

        userInfoDBDaoConfig = daoConfigMap.get(UserInfoDBDao.class).clone();
        userInfoDBDaoConfig.initIdentityScope(type);

        searchNetKeyDBDaoConfig = daoConfigMap.get(SearchNetKeyDBDao.class).clone();
        searchNetKeyDBDaoConfig.initIdentityScope(type);

        searchDBDao = new SearchDBDao(searchDBDaoConfig, this);
        usersDBDao = new UsersDBDao(usersDBDaoConfig, this);
        userInfoDBDao = new UserInfoDBDao(userInfoDBDaoConfig, this);
        searchNetKeyDBDao = new SearchNetKeyDBDao(searchNetKeyDBDaoConfig, this);

        registerDao(SearchDB.class, searchDBDao);
        registerDao(UsersDB.class, usersDBDao);
        registerDao(UserInfoDB.class, userInfoDBDao);
        registerDao(SearchNetKeyDB.class, searchNetKeyDBDao);
    }
    
    public void clear() {
        searchDBDaoConfig.getIdentityScope().clear();
        usersDBDaoConfig.getIdentityScope().clear();
        userInfoDBDaoConfig.getIdentityScope().clear();
        searchNetKeyDBDaoConfig.getIdentityScope().clear();
    }

    public SearchDBDao getSearchDBDao() {
        return searchDBDao;
    }

    public UsersDBDao getUsersDBDao() {
        return usersDBDao;
    }

    public UserInfoDBDao getUserInfoDBDao() {
        return userInfoDBDao;
    }

    public SearchNetKeyDBDao getSearchNetKeyDBDao() {
        return searchNetKeyDBDao;
    }

}
