package flux.lastbus.com.easysobuy.database.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import flux.lastbus.com.easysobuy.database.module.UsersDB;

import flux.lastbus.com.easysobuy.database.module.UserInfoDB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_INFO_DB".
*/
public class UserInfoDBDao extends AbstractDao<UserInfoDB, String> {

    public static final String TABLENAME = "USER_INFO_DB";

    /**
     * Properties of entity UserInfoDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Member_id = new Property(0, String.class, "member_id", true, "MEMBER_ID");
        public final static Property Member_name = new Property(1, String.class, "member_name", false, "MEMBER_NAME");
        public final static Property Member_avatar = new Property(2, String.class, "member_avatar", false, "MEMBER_AVATAR");
        public final static Property Store_name = new Property(3, String.class, "store_name", false, "STORE_NAME");
        public final static Property Grade_id = new Property(4, String.class, "grade_id", false, "GRADE_ID");
        public final static Property Store_id = new Property(5, String.class, "store_id", false, "STORE_ID");
        public final static Property Seller_name = new Property(6, String.class, "seller_name", false, "SELLER_NAME");
        public final static Property Uid = new Property(7, String.class, "uid", false, "UID");
    };

    private DaoSession daoSession;


    public UserInfoDBDao(DaoConfig config) {
        super(config);
    }
    
    public UserInfoDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_INFO_DB\" (" + //
                "\"MEMBER_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: member_id
                "\"MEMBER_NAME\" TEXT," + // 1: member_name
                "\"MEMBER_AVATAR\" TEXT," + // 2: member_avatar
                "\"STORE_NAME\" TEXT," + // 3: store_name
                "\"GRADE_ID\" TEXT," + // 4: grade_id
                "\"STORE_ID\" TEXT," + // 5: store_id
                "\"SELLER_NAME\" TEXT," + // 6: seller_name
                "\"UID\" TEXT);"); // 7: uid
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_INFO_DB\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UserInfoDB entity) {
        stmt.clearBindings();
 
        String member_id = entity.getMember_id();
        if (member_id != null) {
            stmt.bindString(1, member_id);
        }
 
        String member_name = entity.getMember_name();
        if (member_name != null) {
            stmt.bindString(2, member_name);
        }
 
        String member_avatar = entity.getMember_avatar();
        if (member_avatar != null) {
            stmt.bindString(3, member_avatar);
        }
 
        String store_name = entity.getStore_name();
        if (store_name != null) {
            stmt.bindString(4, store_name);
        }
 
        String grade_id = entity.getGrade_id();
        if (grade_id != null) {
            stmt.bindString(5, grade_id);
        }
 
        String store_id = entity.getStore_id();
        if (store_id != null) {
            stmt.bindString(6, store_id);
        }
 
        String seller_name = entity.getSeller_name();
        if (seller_name != null) {
            stmt.bindString(7, seller_name);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(8, uid);
        }
    }

    @Override
    protected void attachEntity(UserInfoDB entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public UserInfoDB readEntity(Cursor cursor, int offset) {
        UserInfoDB entity = new UserInfoDB( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // member_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // member_name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // member_avatar
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // store_name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // grade_id
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // store_id
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // seller_name
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // uid
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UserInfoDB entity, int offset) {
        entity.setMember_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setMember_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMember_avatar(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStore_name(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGrade_id(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setStore_id(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSeller_name(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUid(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(UserInfoDB entity, long rowId) {
        return entity.getMember_id();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(UserInfoDB entity) {
        if(entity != null) {
            return entity.getMember_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUsersDBDao().getAllColumns());
            builder.append(" FROM USER_INFO_DB T");
            builder.append(" LEFT JOIN USERS_DB T0 ON T.\"UID\"=T0.\"UID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected UserInfoDB loadCurrentDeep(Cursor cursor, boolean lock) {
        UserInfoDB entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        UsersDB usersDB = loadCurrentOther(daoSession.getUsersDBDao(), cursor, offset);
        entity.setUsersDB(usersDB);

        return entity;    
    }

    public UserInfoDB loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<UserInfoDB> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<UserInfoDB> list = new ArrayList<UserInfoDB>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<UserInfoDB> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<UserInfoDB> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
